# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\"S\n\x0bUserRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\trecipient\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x1c\n\tUserReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\x13PendingMsgsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07isEmpty\x18\x02 \x01(\x08\x32n\n\x07\x43hatter\x12\"\n\x04\x43hat\x12\x0c.UserRequest\x1a\n.UserReply\"\x00\x12?\n\x17ListenToPendingMessages\x12\x0c.UserRequest\x1a\x14.PendingMsgsResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=14
  _USERREQUEST._serialized_end=97
  _USERREPLY._serialized_start=99
  _USERREPLY._serialized_end=127
  _PENDINGMSGSRESPONSE._serialized_start=129
  _PENDINGMSGSRESPONSE._serialized_end=184
  _CHATTER._serialized_start=186
  _CHATTER._serialized_end=296
# @@protoc_insertion_point(module_scope)
